version: "3"
services:
  rabbit:
    container_name: rabbit
    hostname: rabbit-1
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongo01:/data/db
    restart: always

volumes:
  mongo01:
